### ISSUE TITLE
Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by Bob1979CAN** [0x5e/homebridge-tuya-platform#23]
I have several Temperature and Humidity Sensor from Tuya 
Manufacturer - Tuya Inc.
Model - bguser20

It is identified as an accessory but the value displayed is the battery level for Temperature and Humidity.

**Comment by 0x5e** [comment]
Pkease provide your device's standard instruct and standard status, which can be obtained from tuya platform - device debug, or from homevridge debug logs.

**Comment by Lopatalo** [comment]
Humidity shows well, temperature 100 degrees for all sensors

**Comment by 0x5e** [comment]
Hi @Lopatalo , If something is wrong please give me your device's detail info, thanks

**Comment by Lopatalo** [comment]
> Ahoj@Lopatalo, Pokud je něco špatně, dejte mi prosím podrobné informace o vašem zařízení, děkuji

Product : WIFI温湿度传感器
Device ID : bf9e78fa5d1dd28a7dvfcd
Tuya Inc.
Model : q29ebws5adwye1l8
Firmware : 1.6

**Comment by 0x5e** [comment]
I need standard instruct and standard status @Lopatalo

**Comment by Lopatalo** [comment]
> Potřebuji standardní instrukce a standardní status@Lopatalo

![001](https://user-images.githubusercontent.com/116980314/198871099-331a56cb-3b17-401d-b505-cdcf1f06bb37.jpg)
![002](https://user-images.githubusercontent.com/116980314/198871109-48afd1a6-2cab-4884-9d1b-31083cfa63bc.jpg)
![003](https://user-images.githubusercontent.com/116980314/198871115-8ba250ed-7c0e-49f5-a2c8-b5e32fd26b20.jpg)
![004](https://user-images.githubusercontent.com/116980314/198871118-1866f49f-7388-4bcd-9437-bb6a95fce27b.jpg)
![005](https://user-images.githubusercontent.com/116980314/198871125-d062764b-01a4-484f-b36e-d356c412e977.jpg)
![006](https://user-images.githubusercontent.com/116980314/198871133-d5dc6b2f-6501-4489-a3b1-de54671ad770.jpg)
![007](https://user-images.githubusercontent.com/116980314/198871140-1ab89a7c-02af-483f-9a8d-0651e099a07f.jpg)
![008](https://user-images.githubusercontent.com/116980314/198871144-ec81aa27-0f16-4bf2-9cc0-478f63f3a35d.jpg)

**Comment by 0x5e** [comment]
Your device seems normal. Can you confirm if it is caused by accessory cache?
To clean the cache, please see:
https://github.com/0x5e/homebridge-tuya-platform/issues/24#issuecomment-1296162250

**Comment by 0x5e** [comment]
In Homebridge Web GUI setting page, there's a option to clean accessory cache.

**Comment by Bob1979CAN** [comment]
still not working despite removing cache and installing again the Tuya PlugIn.

**Comment by 0x5e** [comment]
Lopatalo's device instructions are normal. @Bob1979CAN please provide yours, if clean cache is not useful.

**Comment by Lopatalo** [comment]
> Vaše zařízení vypadá normálně. Můžete potvrdit, zda je to způsobeno mezipamětí příslušenství? Chcete-li vyčistit mezipaměť, viz: [#24 (komentář)](https://github.com/0x5e/homebridge-tuya-platform/issues/24#issuecomment-1296162250)
> 
> Pokud bude čistá mezipaměť fungovat, vyčistím mezipaměť pokaždé po upgradu pluginu.

Clearing the cache didn't help. Still the same problem.

**Comment by 0x5e** [comment]
Well, I have no idea now... I will add some logs next version and can you open the debug mode and upload the logs? Thanks.

**Comment by Bob1979CAN** [comment]
I think this is just an api mapping issue.

**Comment by 0x5e** [comment]
> I think this is just an api mapping issue.

Yes, I need some log, every type have different products and my virtual sensor works well, I need logs for the non-working device.

**Comment by MarshallGary** [comment]
Same problem T&H sensor shows temperature 100. Humidity correct. Clean up cache not help.

**Comment by AmitayAbudy** [comment]
@0x5e 
> > I think this is just an api mapping issue.
> 
> Yes, I need some log, every type have different products and my virtual sensor works well, I need logs for the non-working device.

I have the same issue. Here is the relevant log from the api response
`TuyaOpenAPI response: path = /v1.0/homes/69714089/devices, data = {"result":[{"active_time":1667236305,"biz_type":0,"category":"wsdcg","create_time":1667234720,"icon":"smart/icon/ay1525749833414yotNt/d9d4ceec63cb81ff6e8c8d6c2fb4edb3.png","id":"*********","ip":"*********","lat":"","local_key":"*******","lon":"","model":"TH01 CB3S","name":"My sensor","online":true,"owner_id":"******","product_id":"lf36y5nwb8jkxwgg","product_name":"T & H Sensor","status":[{"code":"va_temperature","value":255},{"code":"va_humidity","value":51},{"code":"battery_state","value":"high"},{"code":"temp_unit_convert","value":"c"}]`

I removed some private data, but you can still see the values.
For me the humidity shows as expected, but the temperature stays at 100

**Comment by AmitayAbudy** [comment]
I looked at the code, it looks like at TemperatureHumiditySensorAccessory.ts you are using Math.Min in order to make sure it stays within limit. but the API reports the current temperature without a decimal point (Instead of 25.5C it reports 255C).
So when you're doing Math.Min to the temperature value and 100, it will always be 100.
I think this is the bug's origin. Hope I could help a little :)

**Comment by MarshallGary** [comment]
> I looked at the code, it looks like at TemperatureHumiditySensorAccessory.ts you are using Math.Min in order to make sure it stays within limit. but the API reports the current temperature without a decimal point (Instead of 25.5C it reports 255C).
> So when you're doing Math.Min to the temperature value and 100, it will always be 100.
> I think this is the bug's origin. Hope I could help a little :)

In my case, real value is 21.7... I think 100 is the battery level...
![image](https://user-images.githubusercontent.com/96003663/199309772-fb996c3c-7189-4219-8116-4f55ab4beb29.jpg)
![Uploading 32597A1D-9F94-4C82-988F-381A4B8AE8C0.png…]()

**Comment by AmitayAbudy** [comment]
> In my case, real value is 21.7... I think 100 is the battery level...
Even so. If the real value is 21.7, the api will report it as 217, and when Math.Min will get 100 (Const value) and 217 (Real temperature value) it will return 100. Mine is still reporting 100 even though my battery level is not 100%

**Comment by MarshallGary** [comment]
You right! 
Please prompt me, where I can open source code and add divide to ten...
![Uploading image.jpg…]()

**Comment by hotbird1970** [comment]
I have a similar issue. Temperature and Humidity Sensor shows up in homekit as Temperature sensor only with 100 degrees.

Please see below device details.

"category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "lang_config": {
          "c": "℃",
          "f": "℉"
        },
        "name": "Temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ],
    "status": [
      {
        "code": "va_temperature",
        "lang_config": {
          "unit": "℃"
        },
        "name": "Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}"
      },
      {
        "code": "humidity_value",
        "lang_config": {
          "unit": "%"
        },
        "name": "Current Humidity",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "lang_config": {
          "c": "℃",
          "f": "℉"
        },
        "name": "Temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ]
  },

**Comment by 0x5e** [comment]
Thanks for providing the informations. So this issue is similar to Smart Heater
https://github.com/0x5e/homebridge-tuya-platform/discussions/2#discussioncomment-3990021

We always miss the `scale` option, scale=1 means we should divide the value by `10^1`, scale=0 means divide by `10^0`.

**Comment by MarshallGary** [comment]
Last update beta 1.9 not solve the problem with T&H sensor. Temperature still 100.

**Comment by 0x5e** [comment]
@MarshallGary do you know how to clone and run plugin locally?

The code is here:
https://github.com/0x5e/homebridge-tuya-platform/blob/develop/src/accessory/TemperatureHumiditySensorAccessory.ts#L17-L23

First we get the `va_temperature`'s function property, it should be like this:
```js
{
  unit: "℃",
  min: -200,
  max: 600,
  scale: 1,
  step:1
}
```
The min & max can be ignored because HomeKit has it's on min & max of -270 and 100.
https://developers.homebridge.io/#/service/TemperatureSensor

The temperature value is from `this.device.getDeviceStatus('va_temperature').value` and we should `/ Math.pow(10, property.scale)` before use.

Finally if it still out of [-270, 100] then we strip it.

Please help review and running locally if anyone can, thanks :)

**Comment by MarshallGary** [comment]
> @MarshallGary do you know how to clone and run plugin locally?
> 
> The code is here: https://github.com/0x5e/homebridge-tuya-platform/blob/develop/src/accessory/TemperatureHumiditySensorAccessory.ts#L17-L23
> 
> First we get the `va_temperature`'s function property, it should be like this:
> 
> ```js
> {
>   unit: "℃",
>   min: -200,
>   max: 600,
>   scale: 1,
>   step:1
> }
> ```
> 
> The min & max can be ignored because HomeKit has it's on min & max of -270 and 100. https://developers.homebridge.io/#/service/TemperatureSensor
> 
> The temperature value is from `this.device.getDeviceStatus('va_temperature').value` and we should `/ Math.pow(10, property.scale)` before use.
> 
> Finally if it still out of [-270, 100] then we strip it.
> 
> Please help review and running locally if anyone can, thanks :)

      I don't know how to clone and run. Please help me, I will send you all needed feedback.

**Comment by 0x5e** [comment]
That's a bit difficult to say all the steps in English for me, mostly you can refer this readme to start a plugin develop environment:
https://github.com/homebridge/homebridge-plugin-template

Then you may add some logs before or after the code around `va_temperature`, or I will submit a debug branch for you later.

**Comment by MarshallGary** [comment]
> That's a bit difficult to say all the steps in English for me, mostly you can refer this readme to start a plugin develop environment: https://github.com/homebridge/homebridge-plugin-template
> 
> Then you may add some logs before or after the code around `va_temperature`, or I will submit a debug branch for you later.

    English is non-native for me too. 
    Open repository created from template: https://github.com/MarshallGary/TuyaPlatform-T-and-H-sensor

**Comment by 0x5e** [comment]
read https://github.com/homebridge/homebridge-plugin-template/blob/master/README.md
but clone https://github.com/0x5e/homebridge-tuya-platform develop branch instead :)

**Comment by 0x5e** [comment]
What about this, you create a new account and pair sensor into the account, and provide the username and password to me, let me debug remotely.

**Comment by 0x5e** [comment]
I managed to create a accuracy 0.1 device and have known where the problem is. I can't get `va_temperature`'s scale from `/v1.0/devices/functions`. I need some core modification.

**Comment by MarshallGary** [comment]
> I managed to create a accuracy 0.1 device and have known where the problem is. I can't get `va_temperature`'s scale from `/v1.0/devices/functions`. I need some core modification.

How I can help you?

**Comment by 0x5e** [comment]
It's complicate to say, I can handle this, thanks @MarshallGary .

In the history there's no 'functions' and 'specification' things, they are almost the same thing, just different in write and read. Now the API seperate them then makes me difficult to process.

**Comment by 0x5e** [comment]
Please try beta.20, should fixed now.

**Comment by Lopatalo** [comment]
> Please try beta.20, should fixed now.

It works for me

**Comment by MarshallGary** [comment]
> Please try beta.20, should fixed now.

Yeah!!! Temperature is correct!!! Thank you so much!!!

**Comment by Lopatalo1976** [comment]
> > Please try beta.20, should fixed now.
> 
> Yeah!!! Temperature is correct!!! Thank you so much!!!

Temperature and humidity are not updated in homebridge. Still the same data.

**Comment by hotbird1970** [comment]
Updated to Beta.20 temperature shows correctly in homekit. Many thanks
Any possibility of exposing the Humidity Sensor to homekit.

**Comment by 0x5e** [comment]
> Updated to Beta.20 temperature shows correctly in homekit. Many thanks
> 
> Any possibility of exposing the Humidity Sensor to homekit.

If still not working, please provide homebridge debug log

**Comment by Lopatalo1976** [comment]
Even after 24 hours, the status of the sensors in hombridge has not been updated.

**Comment by 0x5e** [comment]
@Lopatalo1976 We need useful information to solve this problem, "My device is not working" can't help.

**Comment by Lopatalo** [comment]
[log.txt](https://github.com/0x5e/homebridge-tuya-platform/files/9932402/log.txt)

**Comment by hotbird1970** [comment]
@0x5e temperature sensor is working fine, humidity sensor is not appearing. Please see below logs, let me know if this is enough

[2022-11-03, 9:48:56 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667483337}
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=undefined, t=1667483337, 1970-01-20T07:11:23.337Z
currentMessage: dataId=28d26f2d-0d09-4c47-afa7-f401a416e320, t=2, 1970-01-01T00:00:00.002Z
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=12d577b6-9744-49dc-bd93-579513dfa759, t=1667483337, 1970-01-20T07:11:23.337Z
currentMessage: dataId=47b85aa5-2ace-48fb-8a22-25fee8245cd1, t=1667483336, 1970-01-20T07:11:23.336Z
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=71585394-ba2a-41dc-84aa-61f59d86d3fe, t=1667483337, 1970-01-20T07:11:23.337Z
currentMessage: dataId=baf645b7-37bb-41eb-b4c8-dc5063708701, t=1667483336, 1970-01-20T07:11:23.336Z
[2022-11-03, 9:48:57 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 9:56:21 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=offline, bizData={"time":1667483781}
[2022-11-03, 9:56:37 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667483797}
[2022-11-03, 9:57:36 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=offline, bizData={"time":1667483857}
[2022-11-03, 9:57:46 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667483866}
[2022-11-03, 9:59:38 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=e4dedffd-fb85-496f-984d-46e32997ba79, t=1667483978, 1970-01-20T07:11:23.978Z
currentMessage: dataId=555c71dc-2ae0-41be-9d82-125c3b818392, t=1667483977, 1970-01-20T07:11:23.977Z
[2022-11-03, 9:59:38 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 9:59:38 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=e4dedffd-fb85-496f-984d-46e32997ba79, t=1667483978, 1970-01-20T07:11:23.978Z
currentMessage: dataId=5aff1602-36bd-46e9-a1ee-5f646475b020, t=1667483977, 1970-01-20T07:11:23.977Z
[2022-11-03, 9:59:38 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:00:53 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=b710bf59-b66b-4327-aef2-946c285bc7cb, t=1667484053, 1970-01-20T07:11:24.053Z
currentMessage: dataId=fcb46cc8-0627-4aaf-a7f7-b3cee7145367, t=1667484052, 1970-01-20T07:11:24.052Z
[2022-11-03, 10:00:53 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:00:53 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=b710bf59-b66b-4327-aef2-946c285bc7cb, t=1667484053, 1970-01-20T07:11:24.053Z
currentMessage: dataId=43ac7cc7-a245-43a9-a929-72d9f5bf2bac, t=1667484052, 1970-01-20T07:11:24.052Z
[2022-11-03, 10:00:53 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:01:36 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667484097}
[2022-11-03, 10:01:37 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=undefined, t=1667484097, 1970-01-20T07:11:24.097Z
currentMessage: dataId=e45db8b4-d315-4854-8c9f-e6c6ce307978, t=2, 1970-01-01T00:00:00.002Z
[2022-11-03, 10:01:37 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:02:01 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667484121}
[2022-11-03, 10:02:01 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=undefined, t=1667484121, 1970-01-20T07:11:24.121Z
currentMessage: dataId=245b6e36-66d4-49fe-9a98-c13a50b3277d, t=2, 1970-01-01T00:00:00.002Z
[2022-11-03, 10:02:01 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:04:27 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667484267}
[2022-11-03, 10:04:28 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=undefined, t=1667484267, 1970-01-20T07:11:24.267Z
currentMessage: dataId=0df43097-bfee-4e4b-a30b-dab390325fb7, t=2, 1970-01-01T00:00:00.002Z
[2022-11-03, 10:04:28 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[2022-11-03, 10:04:45 a.m.] [@0x5e/homebridge-tuya-platform] Unhandled mqtt message: bizCode=online, bizData={"time":1667484285}
[2022-11-03, 10:04:46 a.m.] [@0x5e/homebridge-tuya-platform] TuyaOpenMQ warning: message received with wrong order.
lastMessage: dataId=undefined, t=1667484285, 1970-01-20T07:11:24.285Z
currentMessage: dataId=30d37502-a300-476d-8207-1fc66cc61951, t=2, 1970-01-01T00:00:00.002Z
[2022-11-03, 10:04:46 a.m.] [@0x5e/homebridge-tuya-platform] Fallback to use API fetching the latest device status.
[11/3/

**Comment by 0x5e** [comment]
@Lopatalo @Lopatalo1976  are you the same one?
From the logs:
```
[03/11/2022, 20:08:44] [TuyaPlatform] TuyaOpenAPI response: path = /v1.0/iot-03/open-hub/access-config, data = {"code":28841101,"msg":"No permissions. This API is not subscribed.","success":false,"t":1667502524334,"tid":"efbe6f5b5baa11ed8a25fe1b67a66e75"}
```

You need to subscribe the following APIs at "Tuya IoT Platform -> Cloud -> Development -> Project -> Service API":
- Authorization Token Management
- Device Status Notification
- IoT Core

Unless it can't receive device status message.
And I will add some logs and instructions when receiving 28841101 error.

**Comment by 0x5e** [comment]
@hotbird1970 Please enable the debug mode before getting logs. I need to see your device detail and logs.

I've updated the Troubleshooting recently:
https://github.com/0x5e/homebridge-tuya-platform#troubleshooting

**Comment by hotbird1970** [comment]
@0x5e  Please let me know if this is enough.

"status": [
    {
      "1": 209,
      "code": "va_temperature",
      "t": "",
      "value": 209
    }
  ]
}
[2022-11-04, 6:32:09 p.m.] [@0x5e/homebridge-tuya-platform] CurrentTemperature: property = { unit: '℃', min: -200, max: 600, scale: 1, step: 1 } multiple = 10 status = { code: 'va_temperature', value: 209 }
[2022-11-04, 6:32:09 p.m.] [@0x5e/homebridge-tuya-platform] Update value 20.900000000000034 => 20.9, subtype=undefined, characteristic=00000011-0000-1000-8000-0026BB765291
[2022-11-04, 6:32:09 p.m.] [@0x5e/homebridge-tuya-platform] [TuyaOpenMQ] onMessage:

protocol = 4
message = {
    "status": [
    {
      "2": 55,
      "code": "humidity_value",
      "t": "",
      "value": 55
    }
  ]
}

**Comment by 0x5e** [comment]
Enough, your humidity code is different than others. Will be added in next beta.

**Comment by 0x5e** [comment]
Please try the latest version and if problem still exists, please tell me. @hotbird1970

**Comment by Bob1979CAN** [comment]
everything is working great. Thanks @0x5e !!

**Comment by hotbird1970** [comment]
Yes, both Temperature and Humidity Sensors now show on homekit
working great thank you

**Comment by Fabi3n31** [comment]
Is there a way to configure the timing to pull the update from tuya platform. It seems to me that the temperature is not updated very often in home app (maybe every hours)

**Comment by 0x5e** [comment]
There's no need to set pull interval, because mqtt is an long connection and it can receive state change immediately. If you can't receive state update, please open an new issue and paste your logs.
